### ISSUE TITLE
Beta Remaining Issues

### ISSUE THREAD

**Issue by IsaacAbrahamson** [BJU-CpS209-Team1/Royale-Platformer#1]
- [x] Player can get stuck on side of wall
- [ ]  Player can go through the top half of a surface

- [x] Enemy players health and armor are not saved/loaded

- [x] Only armor pickups are saved/loaded

**Comment by EliasWatson** [comment]
- [ ] Bullets can glitch through walls
- [ ] Bullets fire too fast
